apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: autoscaling
spec:
  maxReplicas: <Max Pod quantity>
  minReplicas: <Small Pod quantity>
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: <Deploymnet Name>
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: <CPU use percentage>
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: <Memory use percentage>
