apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: podautoscaling
  name: podautoscaling
spec:
  replicas: 3
  selector:
    matchLabels:
      app: podautoscaling
  template:
    metadata:
      labels:
        app: podautoscaling
    spec:
      containers:
      - image: gcr.io/google-samples/hello-app:1.0
        name: hello
        resources:
          requests:
            cpu: <Small mCPU / eg:100m>
            memory: <Small Memory / eg:200Mi>
          limits:
            cpu: <Max mCPU / eg:200m>
            memory: <Max Memory / eg:400Mi>
