apiVersion: v1
kind: Service
metadata:
  labels:
    app: serviceautoscaling
  name: serviceautoscaling
spec:
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30002
    targetPort: 8080
  selector:
    app: podautoscaling
  type: NodePort
