apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodeport
  name: nodeport
spec:
  ports:
  - protocol: TCP
    port: <Internal Service Port>
    nodePort: <External Service Port>
    targetPort: <Pod Port>
  selector:
    app: <Deployment Name>
  type: NodePort
