apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: podclusterip
  name: podclusterip
spec:
  replicas: 3
  selector:
    matchLabels:
      app: podclusterip
  template:
    metadata:
      labels:
        app: podclusterip
    spec:
      containers:
      - image: gcr.io/google-samples/hello-app:1.0
        name: hello
