apiVersion: v1
kind: ConfigMap
metadata:
  name: <configmap name>
data:
  default.conf: |
    server {
      listen       443;
      server_name  localhost;
  
      location / {
          root  /usr/share/nginx/html;
          index index.html index.htm;
      }
    }
