apiVersion: v1
kind: Pod
metadata:
  name: nginx-sidecar-pod
spec:
  containers:
  - name: nginx 
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    volumeMounts:
    - name: shared-logs                   # 掛載名為 shared-logs 的 Volume
      mountPath: /var/log/nginx           # 將 Volume 掛載到 nginx 的 log 資料夾路徑
    resources:
      requests:
        cpu: "200m"
        memory: "128Mi"
      limits:
        cpu: "1000m"
        memory: "256Mi"

  - name: log-agent
    image: busybox
    command: ["/bin/sh", "-c", "tail -n+1 -F /input/nginx/access.log"]

    volumeMounts:
    - name: shared-logs                  # 與主容器共用同一個 Volume
      mountPath: /input/nginx            # 掛載在 log-agent 內部為 /input/nginx

  volumes:
  - name: shared-logs                   # 定義一個名為 shared-logs 的共享 Volume
    emptyDir: {}                        # 使用 emptyDir 類型：當 Pod 被建立時產生，刪除後資料會消失
