apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: hostpath
  name: hostpath
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hostpath
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hostpath
    spec:
      containers:
      - image: busybox
        name: busybox
        command: ["sh", "-c", "while true; do echo $(hostname) $(date) >> /var/log/index.html; sleep 10; done"]
        volumeMounts:
          #èä¿®æ”¹
        - name: <volume name>
          mountPath: /var/log
      volumes:
      - name: <volume name>
        hostPath:
         path: /root/jarry
         type: Directory
