apiVersion: v1
kind: Pod
metadata:
  name: hostpath-demo                    
spec:
  containers:
  - name: nginx                          
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: host-logs                    # 掛載名為 host-logs 的 Volume
      mountPath: /mnt/host-logs          # 容器內路徑：可看到 Node 的 /var/log 內容
    resources:
      requests:
        cpu: "200m"
        memory: "128Mi"
      limits:
        cpu: "1000m"
        memory: "256Mi"            

  volumes:
  - name: host-logs                      # 定義 Volume 名稱
    hostPath:
      path: /var/log/jarry               # Node 上實際要掛載的路徑
      type: DirectoryOrCreate            # 若 Node 上此路徑不存在，則自動建立資料夾
