apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  labels:
    nfs: <tag name>
spec:
  capacity:
    storage: 2G
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: <nfs server ip>
    path: "<file path>"
