apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: podconfigmap
  name: podconfigmap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podconfigmap
  template:
    metadata:
      labels:
        app: podconfigmap
    spec:
      containers:
      - image: nginx:1.14
        name: nginx
        volumeMounts:
        - name: <volume name>
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: <volume name>
        configMap:
          name: <configmap name>
