apiVersion: apps/v1
kind: Deployment
metadata:
  name: secretsmysql
spec:
  selector:
    matchLabels:
      app: secretsmysql
  template:
    metadata:
      labels:
        app: secretsmysql
    spec:
      containers:
      - image: mysql:5.6
        name: secretsmysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: <secret name>
              key: password
        ports:
        - containerPort: 3306
