apiVersion: v1
kind: Service
metadata:
  labels:
    app: servicebingress
  name: servicebingress
spec:
  ports:
  - protocol: TCP
    port: 802
    targetPort: 8080
  selector:
    app: podbingress
  type: NodePort
