apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob
spec:
  schedule: "*/1 * * * *"                # 每分鐘執行一次
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 10        # 執行完成後10秒自動移除
      template:
        spec:
          containers:
          - name: cronjob
            image: busybox:1.28
            command: ["sh", "-c", "echo Hello Jarry"]
          restartPolicy: OnFailure       # 任務失敗才會重新執行
