apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob
spec:
  jobTemplate:
    metadata:
      name: cronjob
    spec:
      template:
        metadata:
        spec:
          containers:
          - image: busybox:1.28
            name: cronjob
            command: ["echo", "Hello Jarry"]
          restartPolicy: OnFailure
  schedule: '*/1 * * * *'
