apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-daemonset              # DaemonSet 名稱
spec:
  selector:
    matchLabels:
      app: nginx                     # 必須與 template.metadata.labels 一致
  template:
    metadata:
      labels:
        app: nginx                   # Pod 標籤
    spec:
      containers:
      - name: nginx                  # 容器名稱
        image: nginx:1.14.2          # 容器 Image 來源（預設 Docker Hub）
        ports:
        - containerPort: 80          # 容器對外服務 Port
        resources:
          requests:
            cpu: "200m"              # 啟動保留 0.5 顆 CPU
            memory: "128Mi"          # 啟動保留 128MiB 記憶體
          limits:
            cpu: "1000m"             # 最多使用 1 顆 CPU
            memory: "256Mi"          # 最多使用 256MiB 記憶體
