apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment             # Deployment 名稱（會影響產生的 Pod 名稱）
spec:
  replicas: 2                        # 想要運行的 Pod 數量
  selector:
    matchLabels:
      app: nginx                     # 與下方 template.metadata.labels 必須一致
  template:
    metadata:
      labels:
        app: nginx                   # Pod 的標籤（供 selector、Service 使用）
    spec:
      containers:
      - name: nginx                  # 容器名稱
        image: nginx:1.14.2          # 容器鏡像
        ports:
        - containerPort: 80          # 容器開放 Port
        resources:
          requests:
            cpu: "500m"              # 最少保留 0.5 顆 CPU
            memory: "128Mi"          # 最少保留 128MiB 記憶體
          limits:
            cpu: "1000m"             # 最多使用 1 顆 CPU
            memory: "256Mi"          # 最多使用 256MiB 記憶體
