apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: job
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: busybox
        name: job
        command: ["sh", "-c", "sleep 5"]
      restartPolicy: Never
