apiVersion: batch/v1
kind: Job
metadata:
  name: simple-job
spec:
  ttlSecondsAfterFinished: 10   # 完成執行後，幾秒內自動刪除
  template:
    metadata:
    spec:
      containers:
      - name: sleep-task
        image: busybox
        command: ["sh", "-c", "sleep 5"]
      restartPolicy: Never        # 必須設定為 Never（或 OnFailure）
